POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "jancoegsekali@gmail.com",
    "password" : "troll123"
}

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoiY3V0amkiLCJlbWFpbCI6ImN1dGppaGFucmlza2FAZ21haWwuY29tIiwiaWF0IjoxNjg1NDEyMzg1LCJleHAiOjE2ODU0MTI0MDV9.1OJFAcovNVVLSWb6I1Y-ZyAk8ce5mjeGX-ThoHetjHE